set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/Users/onurakkaya/.volare/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/Users/onurakkaya/.volare/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/my_first_design"
set ::env(//) "Pin Order"
set ::env(DESIGN_NAME) "my_first_design"
set ::env(VERILOG_FILES) "/openlane/designs/my_first_design/src/my_first_design.v"
set ::env(CLOCK_TREE_SYNTH) "0"
set ::env(CLOCK_PORT) ""
set ::env(PL_RANDOM_GLB_PLACEMENT) "1"
set ::env(FP_SIZING) "absolute"
set ::env(DIE_AREA) "0 0 50 50"
set ::env(PL_TARGET_DENSITY) "0.75"
set ::env(FP_PDN_AUTO_ADJUST) "0"
set ::env(FP_PDN_VPITCH) "25"
set ::env(FP_PDN_HPITCH) "25"
set ::env(FP_PDN_VOFFSET) "5"
set ::env(FP_PDN_HOFFSET) "5"
set ::env(DIODE_INSERTION_STRATEGY) "3"
set ::env(FP_PIN_ORDER_CFG) "/openlane/designs/my_first_design/pin_order.cfg"
